apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
  namespace: argocd
spec:
  project: default
  source:
    helm:
      valueFiles:
        - values-prod.yaml
    repoURL: https://github.com/MekkyMayata/nd064_course_1.git
    targetRevision: HEAD
    path: project/helm/nginx-deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: default